# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"h\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\x03\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\x03\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"+\n\x0fGetPostResponse\x12\x18\n\x04post\x18\x01 \x01(\x0b\x32\n.post.Post\"U\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\x03\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\x03\".\n\x12\x43reatePostResponse\x12\x18\n\x04post\x18\x01 \x01(\x0b\x32\n.post.Post2\x86\x01\n\x0bPostService\x12\x36\n\x07GetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\x12?\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x18.post.CreatePostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=20
  _globals['_POST']._serialized_end=124
  _globals['_GETPOSTREQUEST']._serialized_start=126
  _globals['_GETPOSTREQUEST']._serialized_end=154
  _globals['_GETPOSTRESPONSE']._serialized_start=156
  _globals['_GETPOSTRESPONSE']._serialized_end=199
  _globals['_CREATEPOSTREQUEST']._serialized_start=201
  _globals['_CREATEPOSTREQUEST']._serialized_end=286
  _globals['_CREATEPOSTRESPONSE']._serialized_start=288
  _globals['_CREATEPOSTRESPONSE']._serialized_end=334
  _globals['_POSTSERVICE']._serialized_start=337
  _globals['_POSTSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
